version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-py-3.5
      - test-py-3.8
jobs:
  test-py-3.5:
    docker:
      - image: cimg/python:3.5
    steps:
      - checkout
      - run:
          name: Install tox
          command: |
            pip install tox
      - run:
          name: Run tests
          command: |
            tox -e py35
  test-py-3.8:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install tox
          command: |
            pip install tox
      - run:
          name: Run tests
          command: |
            tox -e py38
